### ISSUE TITLE
MessageFetcher

### ISSUE THREAD

**Issue by fitzyjoe** [TeslaGov/clarakm-aws-events#4]
I'd probably add a constructor to MessageFetcher that takes in the configuration parameters... and then just call getMessage() over and over (fetchFirstMessageBody is an awkward name)

**Comment by kevinmichaelchen** [comment]
I fully support changing `fetchFirstMessageBody` to `getMessage`.

If we change `MessageFetcher` to use constructors instead of static methods, we probably have to apply similar changes to all our helper classes -- for consistency. I don't know that we need to do that, but I don't oppose it.
