### ISSUE TITLE
Constructors or static methods

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/clarakm-aws-events#5]
In #4, @fitzyjoe said
> I'd probably add a constructor to MessageFetcher that takes in the configuration parameters

**Comment by fitzyjoe** [comment]
I checked in some un-tested (but compiles) code in a branch to show you what I mean... but I think I'd like to take it further and get rid of the map that the API holds on to.

**Comment by kevinmichaelchen** [comment]
Make sure you update `README.md`. The code examples will convey why the API has become easier or harder to use.
