### ISSUE TITLE
ManagedAwsApi

### ISSUE THREAD

**Issue by fitzyjoe** [TeslaGov/clarakm-aws-events#6]
createResources() checks for null values of subscriptions and topics, however those will not be null... they'll be empty collections.

You might want to make the constructor private to force use of the builder... after all, the call to createResources() is done as part of the build() call.  Not sure we really need a builder at all though.

Also, do we really want to mix the getMessage() with the publishToTopic() (which should probably be called "publishMessage" in the same class?  It's kind of like mixing sending mail with receiving mail.

It's awkward that ManagedAwsApi.init returns a builder that builds into a ManagedAwsApi.

**Comment by kevinmichaelchen** [comment]
> createResources() checks for null values of subscriptions and topics, however those will not be null... they'll be empty collections.

Good point. I'm not sure if keeping the null check in there was just a defensive instinct of mine (e.g., to guard from untested refactoring). That is, if a dev changes `private final List<Topic> topics = new ArrayList<>();` to `private final List<Topic> topics;`, the program will fail.

> You might want to make the constructor private to force use of the builder... after all, the call to createResources() is done as part of the build() call. Not sure we really need a builder at all though.

It's package-private, so consumers can't use it anyway -- but making it private couldn't hurt.

> Also, do we really want to mix the getMessage() with the publishToTopic() (which should probably be called "publishMessage" in the same class?

I'm just trying to simplify things for consumers. Functional, easy-to-use APIs is really my only goal.

> It's awkward that ManagedAwsApi.init returns a builder that builds into a ManagedAwsApi.

What's awkward about this? Is `init` a bad name? Maybe change it to `newAwsApi`, or `newAwsApiBuilder`, or just `builder`?

**Comment by kevinmichaelchen** [comment]
Regarding your third point, I’m usually the proponent of abstraction and single responsibility, but I can live with having one class. (If you think this is bad, take a look at the infamous Wiki.java).

Going to 2 classes would introduce extra boilerplate for creating that second bean. Plus you’d autowire one for listening and one for sending.

The current class allows apps to use it as a sender only (only topics get created), or as a sender and a listener (topics, queues, and subscriptions get created).

**Comment by kevinmichaelchen** [comment]
I still care about single responsibility. (Every package-private class in this library pretty much does one thing). But I also see consumer value in the Facade Pattern.

**Comment by fitzyjoe** [comment]
The awkward part of that builder/fluent api is that you use class A to get builder B which you use to get class A.  Look at how AWS uses the fluent interface:

```
        AmazonSNS amazonSNS = AmazonSNSClientBuilder
            .standard()
            .withCredentials(awsCredentialsProvider)
            .withRegion(Regions.GovCloud)
            .build();
```

imagine if you had to do this:

```
        AmazonSNSClientBuilder builder = AmazonSNS.init(awsCredentialsProvider);
        AmazonSNS amazonSNS = builder.standard()
            .withRegion(Regions.GovCloud)
            .build();
```

**Comment by kevinmichaelchen** [comment]
In [e7c99aa](https://github.com/TeslaGov/clarakm-aws-events/commit/e7c99aa7914e6f9e24d7e14d086cb6cf87c0c48b), I moved the `init` method to the Builder class.

**Comment by kevinmichaelchen** [comment]
- [ ] should `createResources` return null
- [x] private constructor
- [ ] 1 class vs 2 classes
- [x] move `init()` method to `Builder` class
